version: 2
updates:
  - package-ecosystem: pip
    directory: /webui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /webui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /webui/tests-e2e
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
